### ISSUE TITLE
Project metadata does not save

### ISSUE THREAD

**Issue by sunehajagan** [Blue-Marine-Foundation/Maerl#125] opened 2024-11-28 13:58 UTC
Edits on project metadata table are not being saved on Mearl ("Save Changes" button not working) 
![Image](https://github.com/user-attachments/assets/08e60383-69f3-44aa-9714-30da48db6f6c)

**Comment by samjamead** [comment] 2024-11-28 17:56
Thanks for flagging! This was caused by a little bug that didn't like saving the form if there were no local contacts. Fixed now! Thank you

**Closed by samjamead** 2024-11-28 17:56 UTC
Labels: bug
