### ISSUE TITLE
Impact indicators page 

### ISSUE THREAD

**Issue by sunehajagan** [Blue-Marine-Foundation/Maerl#128] opened 2024-12-05 12:44 UTC
I recall that we used to be able to click on an impact indicator from the "Impact Indicators" page on Mearl and then view all relevant updates under it. But this feature doesn't seem to be present in New Mearl?

**Comment by samjamead** [comment] 2024-12-05 17:00
Hi @sunehajagan this is planned for the next little batch of work, as soon as the current work on filterable updates is published this week. I'll close this issue for now as a duplicate of #116

**Closed by samjamead** 2024-12-05 17:00 UTC
Labels: duplicate
